services:
  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
